sudo: required

language: node_js

node_js: "0.10"

services: mongodb

cache:
    directories:
        - ".meteor"

before_install:
    # fire up xvfb on port :99.0
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # set the xvfb screen size to 1280x1024x16
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

    # install expect
    - "sudo apt-get install expect"
    # install meteor
    - "curl https://install.meteor.com | /bin/sh"

env:
    global:
        - "METEOR_DEPLOY_URL=waiter-free.meteor.com"
script:
    # Test
    - "bash scripts/ci-test.sh"
after_success:
    # Write settings.json
    - 'echo "{\"public\":{\"appEnv\":\"$APP_ENV\"},\"qiniu\":{\"bucket\":\"$QINIU_BUCKET\",\"accessKey\":\"$QINIU_AK\",\"secretKey\":\"$QINIU_SK\",\"domain\":\"$QINIU_DOMAIN\"}}" > private/settings.json'
    # Deploy Staging.
    - "expect scripts/deploy.exp"
    - "sleep 5" #Sleep is to make sure meteor is done deploying
