sudo: required

language: node_js

node_js: "0.10"

services: mongodb

cache:
    directories:
        - ~/.meteor

before_install:
    # install meteor
    - "curl https://install.meteor.com | /bin/sh"
script:
    # Test
    - "bash scripts/ci-test.sh"
    # Deploy Staging
    - "meteor deploy waiter-free.meteor.com"
