sudo: required

language: node_js

node_js: "0.10"

services: mongodb

cache:
    directories:
        - ~/.meteor

before_install:
    # install expect
    - "sudo apt-get install expect"
    # install meteor
    - "curl https://install.meteor.com | /bin/sh"
env:
    global:
        - "METEOR_DEPLOY_URL=waiter-free.meteor.com"
script:
    # Test
    - "bash scripts/ci-test.sh"
after_success:
    # Deploy Staging.
    - "expect scripts/deploy.exp"
    - "sleep 5" #Sleep is to make sure meteor is done deploying
